-- =============================================================================
-- Saunter — launch-week metrics (PRD §10, T+0 to T+7)
-- =============================================================================
--
-- Source of truth: the `tour_events` table (created in lib/pipeline/cache.ts
-- pg() bootstrap). One row per analytics event:
--
--   tour_events(
--     id         bigserial PK,
--     type       text   -- 'generate_request' | 'generate_success'
--                        -- | 'generate_error'  | 'tour_view'
--     city_slug  text,
--     slug       text,
--     ms         int,    -- end-to-end generation time (success/error events)
--     narrated   bool,   -- LLM voice pass ran (currently unset; see note)
--     error      text,   -- error message on generate_error
--     ip_hash    text,   -- sha256(salt:ip)[:16] — NEVER a raw IP
--     created_at timestamptz default now()
--   )
--
-- These queries only run against Postgres. With DATABASE_URL unset the app
-- runs in in-memory mode and writes NO events, so there is simply nothing to
-- query — that is expected, not an error.
--
-- Global limitations / proxy caveats (apply to every query below):
--   * ip_hash is a salted one-way hash. It approximates a "visitor" but
--     collapses everyone behind a shared NAT/VPN/corporate egress to one
--     identity, and splits a single person across networks/devices. Treat all
--     ip_hash counts as ORDER-OF-MAGNITUDE proxies, not exact people.
--   * No team/non-team flag exists. "non-team" in PRD §10 is approximated by
--     "all events" minus whatever you choose to exclude manually (e.g. filter
--     out your office ip_hash list — see the optional exclusion CTE pattern).
--   * Per-step pipeline timing ("geocode", "overpass", ... ) is LOG-ONLY: it
--     is emitted as structured `step.timing` JSON log lines by withTiming() in
--     lib/pipeline/generate.ts and is NOT written to tour_events. Query it via
--     the log backend (e.g. Vercel/Datadog log search on msg="step.timing"),
--     not SQL. End-to-end generation time IS in tour_events.ms below.
--
-- Adjust the launch window in each query (the `created_at >= ...` predicate).
-- Examples use a fixed 7-day rolling window; pin to literal launch dates for
-- the official scorecard, e.g.  created_at >= '2026-06-01' AND created_at < '2026-06-08'.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- §10: "200 tours generated by non-team users."
-- Metric: count of successful generations in the launch window.
-- A generate_success row is written only after generateTour() returns, so this
-- excludes validation rejections and pipeline errors (those are generate_error).
-- Caveat: "non-team" is not modeled. If you maintain a list of team ip_hashes,
-- add  AND ip_hash NOT IN (...)  to approximate non-team usage. Cached-hit
-- generations still count as a success (a user did get a tour), which matches
-- the PRD intent ("a real tour they generated").
-- -----------------------------------------------------------------------------
SELECT count(*) AS tours_generated
FROM tour_events
WHERE type = 'generate_success'
  AND created_at >= now() - interval '7 days';


-- -----------------------------------------------------------------------------
-- §10: "1,000 unique visitors to the landing page."
-- Metric (proxy): distinct ip_hash that triggered a tour_view.
-- Caveat: we instrument tour PAGE views (/[city]/[slug]), not the landing
-- route itself, so this measures "unique people who opened at least one tour"
-- — a conservative lower bound on landing visitors (every tour viewer saw a
-- page, but some landing visitors bounce without opening a tour). For true
-- landing-page uniques use the web-analytics/CDN layer; this is the in-DB
-- proxy. ip_hash NULL rows (header missing) are excluded.
-- -----------------------------------------------------------------------------
SELECT count(DISTINCT ip_hash) AS unique_visitors_proxy
FROM tour_events
WHERE type = 'tour_view'
  AND ip_hash IS NOT NULL
  AND created_at >= now() - interval '7 days';


-- -----------------------------------------------------------------------------
-- §10: "20 tours shared publicly (URL pasted somewhere observable)."
-- Metric (proxy): distinct tour slugs that were viewed from MORE THAN ONE
-- distinct ip_hash. Rationale: a tour the generator never re-shares is only
-- ever seen from its creator's network; a slug seen from multiple networks
-- almost certainly had its URL passed around.
-- Caveats: (a) under-counts shares within one network (office, household);
-- (b) over-counts if the same person opens a tour from phone + laptop on
-- different networks; (c) cannot see the share itself, only the resulting
-- multi-source views. It is a directional proxy, not an exact share count.
-- A looser alternative (raw reach, not "shared"): total tour_view count.
-- -----------------------------------------------------------------------------
SELECT count(*) AS tours_shared_proxy
FROM (
  SELECT slug
  FROM tour_events
  WHERE type = 'tour_view'
    AND slug IS NOT NULL
    AND ip_hash IS NOT NULL
    AND created_at >= now() - interval '7 days'
  GROUP BY slug
  HAVING count(DISTINCT ip_hash) > 1
) multi_source_tours;

-- Looser companion metric: total tour views (raw reach, not de-duplicated).
SELECT count(*) AS total_tour_views
FROM tour_events
WHERE type = 'tour_view'
  AND created_at >= now() - interval '7 days';


-- -----------------------------------------------------------------------------
-- Health: error rate  =  generate_error / generate_request.
-- generate_request is emitted once per validated, rate-limit-passed POST;
-- the request then resolves to exactly one generate_success OR one
-- generate_error, so this ratio is well-defined. PipelineError (bad input /
-- sparse area, HTTP 422) is counted as an error here because it still fired a
-- generate_error event — segment by `error` text if you want to separate
-- "user error" from "pipeline failure".
-- Guards against divide-by-zero (returns 0 when there were no requests).
-- -----------------------------------------------------------------------------
SELECT
  count(*) FILTER (WHERE type = 'generate_request')                         AS requests,
  count(*) FILTER (WHERE type = 'generate_error')                           AS errors,
  count(*) FILTER (WHERE type = 'generate_success')                         AS successes,
  round(
    count(*) FILTER (WHERE type = 'generate_error')::numeric
      / NULLIF(count(*) FILTER (WHERE type = 'generate_request'), 0),
    4
  )                                                                         AS error_rate
FROM tour_events
WHERE type IN ('generate_request', 'generate_success', 'generate_error')
  AND created_at >= now() - interval '7 days';

-- Top error messages (triage which failures dominate the error rate above).
SELECT error, count(*) AS n
FROM tour_events
WHERE type = 'generate_error'
  AND error IS NOT NULL
  AND created_at >= now() - interval '7 days'
GROUP BY error
ORDER BY n DESC
LIMIT 20;


-- -----------------------------------------------------------------------------
-- Performance: p50 / p95 end-to-end generation time (PRD §11 risk: ">60s").
-- ms is wall-clock from just before generateTour() to just after it returns,
-- measured in app/api/generate/route.ts. Computed over generate_success only
-- (errored runs abort early and would skew latency low). Cached hits return
-- in single-digit ms and WILL pull p50 down — that is honest (a real user got
-- an instant tour); split on a future "cached" flag if you need cold-only.
-- Per-STEP latency is log-only (see header note) — not available here.
-- -----------------------------------------------------------------------------
SELECT
  count(*)                                                          AS n,
  round(percentile_cont(0.50) WITHIN GROUP (ORDER BY ms))           AS p50_ms,
  round(percentile_cont(0.95) WITHIN GROUP (ORDER BY ms))           AS p95_ms,
  round(percentile_cont(0.99) WITHIN GROUP (ORDER BY ms))           AS p99_ms,
  max(ms)                                                           AS max_ms
FROM tour_events
WHERE type = 'generate_success'
  AND ms IS NOT NULL
  AND created_at >= now() - interval '7 days';


-- -----------------------------------------------------------------------------
-- Optional: full launch-week scorecard in one row (mirrors
-- cache.ts metricsSummary(); window param is hours, default 168 = 7 days).
-- Handy for a single internal dashboard query.
-- -----------------------------------------------------------------------------
WITH win AS (
  SELECT *
  FROM tour_events
  WHERE created_at >= now() - interval '168 hours'
)
SELECT
  (SELECT count(*) FROM win WHERE type = 'generate_request')               AS generate_requests,
  (SELECT count(*) FROM win WHERE type = 'generate_success')               AS tours_generated,
  (SELECT count(*) FROM win WHERE type = 'generate_error')                 AS generate_errors,
  round(
    (SELECT count(*) FROM win WHERE type = 'generate_error')::numeric
      / NULLIF((SELECT count(*) FROM win WHERE type = 'generate_request'), 0),
    4
  )                                                                        AS error_rate,
  (SELECT count(DISTINCT ip_hash) FROM win
     WHERE type = 'tour_view' AND ip_hash IS NOT NULL)                     AS unique_visitors_proxy,
  (SELECT count(*) FROM win WHERE type = 'tour_view')                      AS total_tour_views,
  (SELECT count(*) FROM (
     SELECT slug FROM win
     WHERE type = 'tour_view' AND slug IS NOT NULL AND ip_hash IS NOT NULL
     GROUP BY slug HAVING count(DISTINCT ip_hash) > 1
   ) s)                                                                    AS tours_shared_proxy,
  (SELECT round(percentile_cont(0.50) WITHIN GROUP (ORDER BY ms))
     FROM win WHERE type = 'generate_success' AND ms IS NOT NULL)          AS p50_ms,
  (SELECT round(percentile_cont(0.95) WITHIN GROUP (ORDER BY ms))
     FROM win WHERE type = 'generate_success' AND ms IS NOT NULL)          AS p95_ms;
